react-beautiful-dnd-horizontal-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        pushd react-beautiful-dnd-horizontal-tryout
          yarn
          yarn build
        popd