mkdir -p PICKERS
mkdir -p 'PICKERS/File Uploader'
mkdir -p 'PICKERS/Menu'
mkdir -p 'PICKERS/Rating'
mkdir -p 'PICKERS/Select'

touch 'PICKERS/File Uploader/index.jsx'
touch 'PICKERS/Menu/index.jsx'
touch 'PICKERS/Rating/index.jsx'
touch 'PICKERS/Select/index.jsx'

mkdir -p DATE_and_TIME
mkdir -p 'DATE_and_TIME/Datepicker'
mkdir -p 'DATE_and_TIME/Time Picker'
mkdir -p 'DATE_and_TIME/Timezone Picker'

touch 'DATE_and_TIME/Datepicker/index.jsx'
touch 'DATE_and_TIME/Time Picker/index.jsx'
touch 'DATE_and_TIME/Timezone Picker/index.jsx'


mkdir -p 'CONTENT'
mkdir -p 'CONTENT/Accordion'
mkdir -p 'CONTENT/Avatar'
mkdir -p 'CONTENT/Drag and Drop List'
mkdir -p 'CONTENT/Layout Grid'
mkdir -p 'CONTENT/Heading'
mkdir -p 'CONTENT/Icon'
mkdir -p 'CONTENT/List'
mkdir -p 'CONTENT/Tag'
mkdir -p 'CONTENT/Tree View'
mkdir -p 'CONTENT/Typography'

touch 'CONTENT/Accordion/index.jsx'
touch 'CONTENT/Avatar/index.jsx'
touch 'CONTENT/Drag and Drop List/index.jsx'
touch 'CONTENT/Layout Grid/index.jsx'
touch 'CONTENT/Heading/index.jsx'
touch 'CONTENT/Icon/index.jsx'
touch 'CONTENT/List/index.jsx'
touch 'CONTENT/Tag/index.jsx'
touch 'CONTENT/Tree View/index.jsx'
touch 'CONTENT/Typography/index.jsx'

mkdir -p 'TABLES'
mkdir -p 'TABLES/Table'
mkdir -p 'TABLES/Data Table'
mkdir -p 'TABLES/Grid Table'
mkdir -p 'TABLES/Flex Table'

touch 'TABLES/Table/index.jsx'
touch 'TABLES/Data Table/index.jsx'
touch 'TABLES/Grid Table/index.jsx'
touch 'TABLES/Flex Table/index.jsx'


mkdir -p 'PROGRESS_and_VALIDATION'
mkdir -p 'PROGRESS_and_VALIDATION/Notification'
mkdir -p 'PROGRESS_and_VALIDATION/Progress Bar'
mkdir -p 'PROGRESS_and_VALIDATION/Progress Steps'
mkdir -p 'PROGRESS_and_VALIDATION/Skeleton'
mkdir -p 'PROGRESS_and_VALIDATION/Snackbar'
mkdir -p 'PROGRESS_and_VALIDATION/Spinner'
mkdir -p 'PROGRESS_and_VALIDATION/Toast'

touch 'PROGRESS_and_VALIDATION/Notification/index.jsx'
touch 'PROGRESS_and_VALIDATION/Progress Bar/index.jsx'
touch 'PROGRESS_and_VALIDATION/Progress Steps/index.jsx'
touch 'PROGRESS_and_VALIDATION/Skeleton/index.jsx'
touch 'PROGRESS_and_VALIDATION/Snackbar/index.jsx'
touch 'PROGRESS_and_VALIDATION/Spinner/index.jsx'
touch 'PROGRESS_and_VALIDATION/Toast/index.jsx'


mkdir -p 'SURFACES'
mkdir -p 'SURFACES/Card'
mkdir -p 'SURFACES/Drawer'
mkdir -p 'SURFACES/Modal'
mkdir -p 'SURFACES/Popover'
mkdir -p 'SURFACES/Tooltip'
touch 'SURFACES/Card/index.jsx'
touch 'SURFACES/Drawer/index.jsx'
touch 'SURFACES/Modal/index.jsx'
touch 'SURFACES/Popover/index.jsx'
touch 'SURFACES/Tooltip/index.jsx'

mkdir -p 'UTILITY'
mkdir -p 'UTILITY/AspectRatioBox'
mkdir -p 'UTILITY/BaseProvider'
mkdir -p 'UTILITY/Block'
mkdir -p 'UTILITY/FlexGrid'
mkdir -p 'UTILITY/Layer'
mkdir -p 'UTILITY/UseStyletron'
mkdir -p 'UTILITY/Styled'
mkdir -p 'UTILITY/Tokens'
mkdir -p 'UTILITY/A11y Validator'

touch 'UTILITY/AspectRatioBox/index.jsx'
touch 'UTILITY/BaseProvider/index.jsx'
touch 'UTILITY/Block/index.jsx'
touch 'UTILITY/FlexGrid/index.jsx'
touch 'UTILITY/Layer/index.jsx'
touch 'UTILITY/UseStyletron/index.jsx'
touch 'UTILITY/Styled/index.jsx'
touch 'UTILITY/Tokens/index.jsx'
touch 'UTILITY/A11y Validator/index.jsx'
