react-router-object-base-route-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        pushd react-router-object-base-route-tryout
          yarn
          yarn build
        popd