# https://docs.drone.io/pipeline/environment/reference/

kind: pipeline
name: helloworld
type: docker

steps:
  - name: helloworld
    image: node:lts
    commands:
      - echo hello
      - echo world
      - echo $DRONE_BRANCH
      - cd react-helloworld-tryout
      - yarn
      - yarn test
      - yarn build
      - cd -

  - name: react-visual-filter-tryout
    image: node:lts
    commands:
      - cd react-visual-filter-tryout
      - yarn
      - yarn build
      - cd -
