react-dropzone-uploader-helloworld-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        pushd react-dropzone-uploader-helloworld-tryout
          yarn
          yarn build
        popd