const LYNKED_RED = "#B71D1B";
const LYNKED_RED_HOVER = "#EB2723";

const LYNKED_WHITE = "#FFFFFF";

const LYNKED_BLACK_HOVER = "#4D4D4D";
const LYNKED_BLACK = "#000000";

const LYNKED_DEEP_GREY_HOVER = "#CCCCCC";
const LYNKED_DEEP_GREY = "#9A9A9A";

const LYNKED_LIGHT_GREY_HOVER = "#E6E6E6";
const LYNKED_LIGHT_GREY = "#B3B3B3";

const LYNKED_BLUE_HOVER = "#4F68E8";
const LYNKED_BLUE = "#3E51B5";

const LYNKED_GREEN_HOVER = "#5BD461";
const LYNKED_GREEN = "#44A048";

const LYNKED_SUCCESS = LYNKED_GREEN;

export {
  LYNKED_RED,
  LYNKED_RED_HOVER,
  LYNKED_WHITE,
  LYNKED_BLACK_HOVER,
  LYNKED_BLACK,
  LYNKED_LIGHT_GREY_HOVER,
  LYNKED_LIGHT_GREY,
  LYNKED_DEEP_GREY_HOVER,
  LYNKED_DEEP_GREY,
  LYNKED_SUCCESS,
  LYNKED_GREEN,
  LYNKED_GREEN_HOVER,
  LYNKED_BLUE,
  LYNKED_BLUE_HOVER,
};
