react-browser-detection-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        pushd react-browser-detection-tryout
          yarn
          yarn build
        popd