react-formik-material-ui-autocomplete-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        pushd react-formik-material-ui-autocomplete-tryout
          yarn
          yarn build
        popd