react-formik-radio-button-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        pushd react-formik-radio-button-tryout
          yarn
          yarn build
        popd