react-stripe-setup-payouts-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        pushd react-stripe-setup-payouts-tryout
          yarn
          yarn build
        popd