react-loading-spinkit-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        pushd react-loading-spinkit-tryout
          yarn
          yarn build
        popd