react-qr-code-with-frame-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        pushd react-qr-code-with-frame-tryout
          yarn
          yarn build
        popd