react-send-get-request-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        pushd react-send-get-request-tryout
          yarn
          yarn build
        popd