react-calendar-heatmap-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        pushd react-calendar-heatmap-tryout
          yarn
          yarn build
        popd