react-hide-console-message-in-production-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        pushd react-hide-console-message-in-production-tryout
          yarn
          yarn build
        popd