import { ColorLuminance } from 'src/consts/ColorLuminance';

const LYNKED_DANGER = '#e74c3c';
const LYNKED_DANGER_HOVER = ColorLuminance(LYNKED_DANGER, 0.2);
const LYNKED_DANGER_SUPER_LIGHT = ColorLuminance(LYNKED_DANGER, 0.4);
const LYNKED_DANGER_BACKGROUND = '#c0392b';
const LYNKED_DANGER_DARKEN = ColorLuminance(LYNKED_DANGER, -0.4);

const LYNKED_PRIMARY = '#800000';
const LYNKED_PRIMARY_HOVER = ColorLuminance(LYNKED_PRIMARY, 0.2);
const LYNKED_PRIMARY_SUPER_LIGHT = ColorLuminance(LYNKED_PRIMARY, 0.4);
const LYNKED_PRIMARY_BACKGROUND = '#CCACAC';
const LYNKED_PRIMARY_DARKEN = ColorLuminance(LYNKED_PRIMARY, -0.4);

const LYNKED_SECONDARY = '#800000';
const LYNKED_SECONDARY_HOVER = ColorLuminance(LYNKED_SECONDARY, 0.2);
const LYNKED_SECONDARY_SUPER_LIGHT = ColorLuminance(LYNKED_SECONDARY, 0.4);
const LYNKED_SECONDARY_BACKGROUND = '#CCACAC';
const LYNKED_SECONDARY_DARKEN = ColorLuminance(LYNKED_SECONDARY, -0.4);

const LYNKED_INFO = '#3E51B5';
const LYNKED_INFO_HOVER = ColorLuminance(LYNKED_INFO, 0.2);
const LYNKED_INFO_SUPER_LIGHT = ColorLuminance(LYNKED_INFO, 0.4);
const LYNKED_INFO_BACKGROUND = '#CCACAC';
const LYNKED_INFO_DARKEN = ColorLuminance(LYNKED_INFO, -0.4);

const LYNKED_SUCCESS = '#27ae60';
const LYNKED_SUCCESS_HOVER = ColorLuminance(LYNKED_SUCCESS, 0.2);
const LYNKED_SUCCESS_SUPER_LIGHT = ColorLuminance(LYNKED_SUCCESS, 0.4);
const LYNKED_SUCCESS_BACKGROUND = '#CCACAC';
const LYNKED_SUCCESS_DARKEN = ColorLuminance(LYNKED_SUCCESS, -0.4);

const LYNKED_WARNING = '#f39c12';
const LYNKED_WARNING_HOVER = ColorLuminance(LYNKED_WARNING, 0.2);
const LYNKED_WARNING_SUPER_LIGHT = ColorLuminance(LYNKED_WARNING, 0.4);
const LYNKED_WARNING_BACKGROUND = '#CCACAC';
const LYNKED_WARNING_DARKEN = ColorLuminance(LYNKED_WARNING, -0.4);

const LYNKED_MUTED = '#B3B3B3';
const LYNKED_MUTED_HOVER = ColorLuminance(LYNKED_MUTED, 0.2);
const LYNKED_MUTED_SUPER_LIGHT = ColorLuminance(LYNKED_MUTED, 0.4);
const LYNKED_MUTED_BACKGROUND = '#CCACAC';
const LYNKED_MUTED_DARKEN = ColorLuminance(LYNKED_MUTED, -0.4);

const LYNKED_WHITE = '#FFFFFF';
const LYNKED_WHITE_HOVER = '#CCCCCC';

const LYNKED_DEEP_GREY = '#9A9A9A';
const LYNKED_DEEP_GREY_HOVER = '#CCCCCC';

// const LYNKED_LIGHT_GREY_HOVER = '#E6E6E6';
// const LYNKED_LIGHT_GREY = '#B3B3B3';

// const LYNKED_GREEN_HOVER = '#5BD461';

// const LYNKED_BORDER_GREY = '#F4F6F8';

// const LYNKED_SUCCESS = LYNKED_GREEN;

// const LYNKED_BACKGROUND_LIGHT_GREY = ColorLuminance(LYNKED_LIGHT_GREY, 0.4);

// const LYNKED_NAV_HIGHLIGHT = '#E2EDFF';

// const LYNKED_BLACK = '#000000';
// const LYNKED_BLACK_HOVER = '#333333';
// // const LYNKED_BLACK_HOVER = ColorLuminan

// const BORDER_COLOR = '#E0E0E0';

const LYNKED_RED = LYNKED_DANGER;
const LYNKED_RED_HOVER = LYNKED_DANGER_HOVER;

export {
  LYNKED_RED,
  LYNKED_RED_HOVER,
  LYNKED_DEEP_GREY,
  LYNKED_DEEP_GREY_HOVER,
  LYNKED_DANGER,
  LYNKED_DANGER_HOVER,
  LYNKED_DANGER_SUPER_LIGHT,
  LYNKED_DANGER_BACKGROUND,
  LYNKED_DANGER_DARKEN,
  LYNKED_PRIMARY,
  LYNKED_PRIMARY_HOVER,
  LYNKED_PRIMARY_SUPER_LIGHT,
  LYNKED_PRIMARY_BACKGROUND,
  LYNKED_PRIMARY_DARKEN,
  LYNKED_SECONDARY,
  LYNKED_SECONDARY_HOVER,
  LYNKED_SECONDARY_SUPER_LIGHT,
  LYNKED_SECONDARY_BACKGROUND,
  LYNKED_SECONDARY_DARKEN,
  LYNKED_INFO,
  LYNKED_INFO_HOVER,
  LYNKED_INFO_SUPER_LIGHT,
  LYNKED_INFO_BACKGROUND,
  LYNKED_INFO_DARKEN,
  LYNKED_SUCCESS,
  LYNKED_SUCCESS_HOVER,
  LYNKED_SUCCESS_SUPER_LIGHT,
  LYNKED_SUCCESS_BACKGROUND,
  LYNKED_SUCCESS_DARKEN,
  LYNKED_WARNING,
  LYNKED_WARNING_HOVER,
  LYNKED_WARNING_SUPER_LIGHT,
  LYNKED_WARNING_BACKGROUND,
  LYNKED_WARNING_DARKEN,
  LYNKED_MUTED,
  LYNKED_MUTED_HOVER,
  LYNKED_MUTED_SUPER_LIGHT,
  LYNKED_MUTED_BACKGROUND,
  LYNKED_MUTED_DARKEN,
  LYNKED_WHITE,
  LYNKED_WHITE_HOVER,
};
