# CREDIT: https://github.com/shren207/nextjs-docker-compose
services:
  test:
    build: .
    ports:
      - 3000
    restart: always
    user: 1000:1000

    working_dir: /app
    volumes:
      - $PWD:/app
      - test_node_modules:/app/node_modules
    command: sleep infinity

    # labels:
    #   - 'traefik.enable=true'
    #   - 'traefik.http.routers.whoami.rule=Host(`portfolio.iamon99.com`)'
    #   - 'traefik.http.routers.whoami.entrypoints=websecure'
    #   - 'traefik.http.routers.whoami.tls.certresolver=myresolver'
    
volumes:
  test_node_modules:
