react-block-and-then-redirect-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        pushd react-block-and-then-redirect-tryout
          yarn
          yarn build
        popd