react-toast-notifications-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        pushd react-toast-notifications-tryout
          yarn
          yarn build
        popd