react-router-dom-layout-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        pushd react-router-dom-layout-tryout
          yarn
          yarn build
        popd