react-my-image-upload-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        pushd react-my-image-upload-tryout
          yarn
          yarn build
        popd