react-top-loading-bar-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        pushd react-top-loading-bar-tryout
          yarn
          yarn build
        popd