react-firebase-cloud-storage-helloworld-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        pushd react-firebase-cloud-storage-helloworld-tryout
          yarn
          yarn build
        popd