react-upload-and-organize-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        pushd react-upload-and-organize-tryout
          yarn
          yarn build
        popd