const fs = require('fs');
const path = require('path');
const CWD = path.resolve(__dirname);
const PROJ_ROOT = path.dirname(CWD);

console.log('helloworld');

fs.readdirSync('.').forEach((root_dirs) => {
  // console.log(dirs);
  // console.log(PROJ_ROOT);
  if (root_dirs.indexOf('react') > -1) {
    try {
      fs.writeFileSync(
        `${PROJ_ROOT}/${root_dirs}/scripts/dev.bat`,
        `
: generated by D:\\_workspace\\react-playlist\\scripts\\init_dev_bat.js

set BROWSER=none

call yarn install 

yarn start
        `.trim(),
        { create: true }
      );
    } catch (error) {
      console.log(error);
    }
  }
});
