#!/usr/bin/env sh

git checkout -b let-the-user-select-something-while-typing/react-autocomplete-input/helloworld
git checkout -b let-the-user-select-something-while-typing/react-mentions/helloworld
git checkout -b let-the-user-add-multiple-tags-in-a-single-input/@pathofdev/react-tag-input/helloworld
git checkout -b let-the-user-add-multiple-tags-in-a-single-input/react-tag-input/helloworld
git checkout -b let-the-user-add-multiple-tags-in-a-single-input/react-tagsinput/helloworld
git checkout -b let-the-user-add-multiple-tags-in-a-single-input/react-tokeninput/helloworld
git checkout -b autosize-input-textarea/react-input-autosize/helloworld
git checkout -b autosize-input-textarea/react-textarea-autosize/helloworld
git checkout -b star-rating/react-awesome-stars-rating/helloworld
git checkout -b star-rating/react-star-rating-input/helloworld
git checkout -b star-rating/react-star-rating/helloworld
git checkout -b drag-and-drop/react-beautiful-dnd/helloworld
git checkout -b drag-and-drop/react-dnd/helloworld
git checkout -b drag-and-drop/react-draggable/helloworld
git checkout -b drag-and-drop/react-dragula/helloworld
git checkout -b drag-and-drop/react-droparea/helloworld
git checkout -b drag-and-drop/react-dropzone/helloworld
git checkout -b drag-and-drop/react-sortable-pane/helloworld
git checkout -b let-the-user-define-an-order-on-a-list/react-anything-sortable/helloworld
git checkout -b let-the-user-define-an-order-on-a-list/react-sortable-hoc/helloworld
git checkout -b let-the-user-define-an-order-on-a-list/react-sortable/helloworld
git checkout -b let-the-user-define-an-order-on-a-list/sortablejs/helloworld
git checkout -b rich-text-editor/alloyeditor/helloworld
git checkout -b rich-text-editor/draft-js/helloworld
git checkout -b rich-text-editor/megadraft/helloworld
git checkout -b rich-text-editor/react-ace/helloworld
git checkout -b rich-text-editor/react-codemirror/helloworld
git checkout -b rich-text-editor/react-contenteditable/helloworld
git checkout -b rich-text-editor/react-draft-wysiwyg/helloworld
git checkout -b rich-text-editor/react-medium-editor/helloworld
git checkout -b rich-text-editor/react-quill/helloworld
git checkout -b rich-text-editor/react-trumbowyg/helloworld
git checkout -b rich-text-editor/ritzy/helloworld
git checkout -b markdown-editor/react-markdown-editor/helloworld
git checkout -b markdown-editor/react-md-editor/helloworld
git checkout -b image-manipulation/react-avatar-cropper/helloworld
git checkout -b image-manipulation/react-avatar-editor/helloworld
git checkout -b image-manipulation/react-image-crop/helloworld
git checkout -b image-manipulation/react-image-cropper/helloworld
git checkout -b form-component-collections/formsy-material-ui/helloworld
git checkout -b form-component-collections/formsy-react-components/helloworld
git checkout -b form-component-collections/react-input-enhancements/helloworld
git checkout -b form-component-collections/react-widgets/helloworld
git checkout -b miscellaneous/react-designer/helloworld
git checkout -b miscellaneous/react-images-uploader/helloworld
git checkout -b miscellaneous/react-upload-gallery/helloworld
git checkout -b syntax-highlight/react-syntax-highlighter/helloworld
git checkout -b components-to-layout-the-app's-ui/autoresponsive-react/helloworld
git checkout -b flexbox-react-unopinionated-standard-compliant-flexbox-components/golden-layout/helloworld
git checkout -b flexbox-react-unopinionated-standard-compliant-flexbox-components/hedron/helloworld
git checkout -b flexbox-react-unopinionated-standard-compliant-flexbox-components/m-react-splitters/helloworld
git checkout -b flexbox-react-unopinionated-standard-compliant-flexbox-components/react-flexbox-grid/helloworld
git checkout -b flexbox-react-unopinionated-standard-compliant-flexbox-components/react-grid-layout/helloworld
git checkout -b flexbox-react-unopinionated-standard-compliant-flexbox-components/react-masonry-component/helloworld
git checkout -b flexbox-react-unopinionated-standard-compliant-flexbox-components/react-reflex/helloworld
git checkout -b flexbox-react-unopinionated-standard-compliant-flexbox-components/react-spaces/helloworld
git checkout -b flexbox-react-unopinionated-standard-compliant-flexbox-components/react-stack-grid/helloworld
git checkout -b flexbox-react-unopinionated-standard-compliant-flexbox-components/react-stonecutter/helloworld
git checkout -b animate-transitions/animakit-elastic/helloworld
git checkout -b animate-transitions/animakit-expander/helloworld
git checkout -b animate-transitions/animakit-rotator/helloworld
git checkout -b animate-transitions/data-driven-motion/helloworld
git checkout -b animate-transitions/react-anime/helloworld
git checkout -b animate-transitions/react-flip-move/helloworld
git checkout -b animate-transitions/react-gsap-enhancer/helloworld
git checkout -b animate-transitions/react-magic-move/helloworld
git checkout -b animate-transitions/react-motion-ui-pack/helloworld
git checkout -b animate-transitions/react-motion/helloworld
git checkout -b animate-transitions/react-mt-svg-lines/helloworld
git checkout -b animate-transitions/react-router-transition/helloworld
git checkout -b animate-transitions/react-spring/helloworld
git checkout -b animate-transitions/react-spark-scroll/helloworld
git checkout -b animate-transitions/react-track/helloworld
git checkout -b animate-transitions/react-transitive-number/helloworld
git checkout -b animate-transitions/react-tween-state/helloworld
git checkout -b animate-transitions/react-tween/helloworld
git checkout -b animate-transitions/react-web-animation/helloworld
git checkout -b animate-transitions/react.animate/helloworld
git checkout -b animate-transitions/velocity-react/helloworld
git checkout -b animate-transitions/react-scroll-rotate/helloworld
git checkout -b animate-transitions/react-particles-bg/helloworld
git checkout -b parallax/react-parallax-component/helloworld
git checkout -b parallax/react-parallax-tilt/helloworld
git checkout -b set-of-components-and-responsive-layout-system/rocket ant-design/helloworld
git checkout -b set-of-components-and-responsive-layout-system/rc-tooltip/helloworld
git checkout -b set-of-components-and-responsive-layout-system/rc-menu/helloworld
git checkout -b set-of-components-and-responsive-layout-system/rc-animate/helloworld
git checkout -b set-of-components-and-responsive-layout-system/rc-slider/helloworld
git checkout -b set-of-components-and-responsive-layout-system/rc-calendar/helloworld
git checkout -b set-of-components-and-responsive-layout-system/rc-progress/helloworld
git checkout -b set-of-components-and-responsive-layout-system/atlaskit/helloworld
git checkout -b set-of-components-and-responsive-layout-system/base web/helloworld
git checkout -b set-of-components-and-responsive-layout-system/belle/helloworld
git checkout -b set-of-components-and-responsive-layout-system/blueprint/helloworld
git checkout -b set-of-components-and-responsive-layout-system/carbon/helloworld
git checkout -b set-of-components-and-responsive-layout-system/elemental/helloworld
git checkout -b set-of-components-and-responsive-layout-system/grommet/helloworld
git checkout -b set-of-components-and-responsive-layout-system/gestalt/helloworld
git checkout -b set-of-components-and-responsive-layout-system/pivotal-ui-react/helloworld
git checkout -b set-of-components-and-responsive-layout-system/office-ui-fabric-react/helloworld
git checkout -b set-of-components-and-responsive-layout-system/rctui/helloworld
git checkout -b set-of-components-and-responsive-layout-system/react-foundation-apps/helloworld
git checkout -b set-of-components-and-responsive-layout-system/react-foundation/helloworld
git checkout -b set-of-components-and-responsive-layout-system/reakit/helloworld
git checkout -b set-of-components-and-responsive-layout-system/rebass/helloworld
git checkout -b set-of-components-and-responsive-layout-system/rsuite/helloworld
git checkout -b set-of-components-and-responsive-layout-system/searchkit/helloworld
git checkout -b set-of-components-and-responsive-layout-system/semantic-ui-react/helloworld
git checkout -b set-of-components-and-responsive-layout-system/fluent-ui/helloworld
git checkout -b material-design/rocket Material-UI/helloworld
git checkout -b material-design/Modal/helloworld
git checkout -b material-design/Icons/helloworld
git checkout -b material-design/Slider/helloworld
git checkout -b material-design/Autocomplete/helloworld
git checkout -b material-design/Tree View/helloworld
git checkout -b material-design/OnsenUI/helloworld
git checkout -b material-design/react-essence/helloworld
git checkout -b material-design/react-materialize/helloworld
git checkout -b material-design/react-toolbox/helloworld
git checkout -b mobile/antd-mobile/helloworld
git checkout -b mobile/reactionic/helloworld
git checkout -b mobile/touchstonejs/helloworld
git checkout -b component-collections/dataminr-react-components/helloworld
git checkout -b component-collections/shards-react/helloworld
git checkout -b component-collections/aframe-react/helloworld
git checkout -b component-collections/react-admin/helloworld
git checkout -b component-collections/react-desktop/helloworld
git checkout -b component-collections/react-stack-cards/helloworld
git checkout -b report-when-a-component-becomes-visiblehidden/react-visibility-sensor/helloworld
git checkout -b report-when-a-component-becomes-visiblehidden/react-waypoint/helloworld
git checkout -b determine-and-report-measurements-of-an-element/react-component-queries/helloworld
git checkout -b determine-and-report-measurements-of-an-element/react-container-dimensions/helloworld
git checkout -b determine-and-report-measurements-of-an-element/react-dimensions/helloworld
git checkout -b determine-and-report-measurements-of-an-element/react-height-reporter/helloworld
git checkout -b determine-and-report-measurements-of-an-element/react-height/helloworld
git checkout -b determine-and-report-measurements-of-an-element/react-measure/helloworld
git checkout -b determine-and-report-measurements-of-an-element/react-sizeme/helloworld
git checkout -b keyboard-events/react-hotkeys/helloworld
git checkout -b keyboard-events/react-key-handler/helloworld
git checkout -b keyboard-events/react-keydown/helloworld
git checkout -b keyboard-events/react-shortcuts/helloworld
git checkout -b scroll-events/react-scroll-components/helloworld
git checkout -b touch-swipe/react-swipe/helloworld
git checkout -b mouse-events/react-aim/helloworld
git checkout -b mouse-events/react-hook-mighty-mouse/helloworld
git checkout -b set-meta-tags-<title>-children-of/react-document-meta/helloworld
git checkout -b set-meta-tags-<title>-children-of/react-document-title/helloworld
git checkout -b set-meta-tags-<title>-children-of/react-helmet/helloworld
git checkout -b render-an-element-at-an-arbitrary-dom-node/react-gateway/helloworld
git checkout -b render-an-element-at-an-arbitrary-dom-node/react-layer-stack/helloworld
git checkout -b render-an-element-at-an-arbitrary-dom-node/react-portal/helloworld
git checkout -b ab-tests-experiments/react-ab/helloworld
git checkout -b ab-tests-experiments/react-experiments/helloworld
git checkout -b data-flow-data-management-data-stores-components-state-data-flow/alt/helloworld
git checkout -b data-flow-data-management-data-stores-components-state-data-flow/baobab-react/helloworld
git checkout -b data-flow-data-management-data-stores-components-state-data-flow/cerebral/helloworld
git checkout -b data-flow-data-management-data-stores-components-state-data-flow/fluorine-lib/helloworld
git checkout -b data-flow-data-management-data-stores-components-state-data-flow/fluxible/helloworld
git checkout -b data-flow-data-management-data-stores-components-state-data-flow/fluxxor/helloworld
git checkout -b data-flow-data-management-data-stores-components-state-data-flow/kea/helloworld
git checkout -b data-flow-data-management-data-stores-components-state-data-flow/mobx-react/helloworld
git checkout -b data-flow-data-management-data-stores-components-state-data-flow/react-3ducks/helloworld
git checkout -b data-flow-data-management-data-stores-components-state-data-flow/react-controllables/helloworld
git checkout -b data-flow-data-management-data-stores-components-state-data-flow/react-i13n/helloworld
git checkout -b data-flow-data-management-data-stores-components-state-data-flow/react-redux-provide/helloworld
git checkout -b data-flow-data-management-data-stores-components-state-data-flow/react-redux/helloworld
git checkout -b data-flow-data-management-data-stores-components-state-data-flow/react-storage-hoc/helloworld
git checkout -b data-flow-data-management-data-stores-components-state-data-flow/recompose/helloworld
git checkout -b data-flow-data-management-data-stores-components-state-data-flow/redux-batched-actions/helloworld
git checkout -b data-flow-data-management-data-stores-components-state-data-flow/redux-batched-subscribe/helloworld
git checkout -b data-flow-data-management-data-stores-components-state-data-flow/redux/helloworld
git checkout -b data-flow-data-management-data-stores-components-state-data-flow/reflux/helloworld
git checkout -b data-flow-data-management-data-stores-components-state-data-flow/reselect/helloworld
git checkout -b data-flow-data-management-data-stores-components-state-data-flow/shasta/helloworld
git checkout -b form-logic/formcat/helloworld
git checkout -b form-logic/formik/helloworld
git checkout -b form-logic/formsy-react/helloworld
git checkout -b form-logic/plexus-form/helloworld
git checkout -b form-logic/react-hook-form/helloworld
git checkout -b form-logic/react-jsonschema-form/helloworld
git checkout -b form-logic/react-validation-mixin/helloworld
git checkout -b form-logic/react-final-form/helloworld
git checkout -b form-logic/react-formawesome/helloworld
git checkout -b form-logic/surveyjs/helloworld
git checkout -b form-logic/tcomb-form/helloworld
git checkout -b form-logic/winterfell/helloworld
git checkout -b router/cerebral-module-router/helloworld
git checkout -b router/monorouter/helloworld
git checkout -b router/react-breadcrumbs/helloworld
git checkout -b router/react-router-component/helloworld
git checkout -b router/react-router-scroll/helloworld
git checkout -b router/react-router/helloworld
git checkout -b router/redux-router/helloworld
git checkout -b router/universal-router/helloworld
git checkout -b router/redux-first-history/helloworld
git checkout -b component-properties-asynchronously-fetched-over-the-network/react-async/helloworld
git checkout -b component-properties-asynchronously-fetched-over-the-network/react-refetch/helloworld
git checkout -b component-properties-asynchronously-fetched-over-the-network/react-resolver/helloworld
git checkout -b component-properties-asynchronously-fetched-over-the-network/react-router-relay/helloworld
git checkout -b component-properties-asynchronously-fetched-over-the-network/redial/helloworld
git checkout -b component-properties-asynchronously-fetched-over-the-network/redux-async-connect/helloworld
git checkout -b component-properties-asynchronously-fetched-over-the-network/redux-connect/helloworld
git checkout -b communication-with-server/adrenaline/helloworld
git checkout -b communication-with-server/apollo-client/helloworld
git checkout -b communication-with-server/cerebral-module-http/helloworld
git checkout -b communication-with-server/react-apollo/helloworld
git checkout -b communication-with-server/react-relay/helloworld
git checkout -b communication-with-server/react-transmit/helloworld
git checkout -b css-style/aphrodite/helloworld
git checkout -b css-style/classnames/helloworld
git checkout -b css-style/inline-style-prefixer/helloworld
git checkout -b css-style/postcss-js/helloworld
git checkout -b css-style/radium/helloworld
git checkout -b css-style/react-container-query/helloworld
git checkout -b css-style/react-css-modules/helloworld
git checkout -b css-style/react-responsive/helloworld
git checkout -b css-style/styled-components/helloworld
git checkout -b html-template/hyperx/helloworld
git checkout -b html-template/jsx-control-statements/helloworld
git checkout -b html-template/react-templates/helloworld
git checkout -b isomorphic-apps/hypernova/helloworld
git checkout -b isomorphic-apps/isomorphic-relay/helloworld
git checkout -b isomorphic-apps/isomorphic-style-loader/helloworld
git checkout -b isomorphic-apps/react-server/helloworld
git checkout -b isomorphic-apps/rill/helloworld
git checkout -b isomorphic-apps/webpack-isomorphic-tools/helloworld
git checkout -b scaffold-starter-kit-yeoman-generator-stack-ensemble-seed/create-react-app/helloworld
git checkout -b scaffold-starter-kit-yeoman-generator-stack-ensemble-seed/electron-react-boilerplate/helloworld
git checkout -b scaffold-starter-kit-yeoman-generator-stack-ensemble-seed/essential-react/helloworld
git checkout -b scaffold-starter-kit-yeoman-generator-stack-ensemble-seed/generator-flux-on-rails/helloworld
git checkout -b scaffold-starter-kit-yeoman-generator-stack-ensemble-seed/generator-react-webpack/helloworld
git checkout -b scaffold-starter-kit-yeoman-generator-stack-ensemble-seed/generator-starhackit/helloworld
git checkout -b scaffold-starter-kit-yeoman-generator-stack-ensemble-seed/gluestick/helloworld
git checkout -b scaffold-starter-kit-yeoman-generator-stack-ensemble-seed/nwb/helloworld
git checkout -b scaffold-starter-kit-yeoman-generator-stack-ensemble-seed/react-boilerplate/helloworld
git checkout -b scaffold-starter-kit-yeoman-generator-stack-ensemble-seed/react-hot-boilerplate/helloworld
git checkout -b scaffold-starter-kit-yeoman-generator-stack-ensemble-seed/react-redux-universal-hot-example/helloworld
git checkout -b scaffold-starter-kit-yeoman-generator-stack-ensemble-seed/reactuate/helloworld
git checkout -b scaffold-starter-kit-yeoman-generator-stack-ensemble-seed/redux-cli/helloworld
git checkout -b scaffold-starter-kit-yeoman-generator-stack-ensemble-seed/relay-fullstack/helloworld
git checkout -b scaffold-starter-kit-yeoman-generator-stack-ensemble-seed/roc/helloworld
git checkout -b scaffold-starter-kit-yeoman-generator-stack-ensemble-seed/universal-redux/helloworld
git checkout -b scaffold-starter-kit-yeoman-generator-stack-ensemble-seed/create-react-dependency/helloworld
git checkout -b miscellaneous/react-inlinesvg/helloworld
git checkout -b miscellaneous/redux-auth-patch/helloworld
git checkout -b miscellaneous/redux-search/helloworld
git checkout -b miscellaneous/tcomb-react/helloworld
git checkout -b miscellaneous/react-find/helloworld
git checkout -b utilities/qrcode.react/helloworld
git checkout -b utilities/react-children-utilities/helloworld
git checkout -b utilities/react-faux-dom/helloworld
git checkout -b utilities/react-media/helloworld
git checkout -b utilities/react-middle-ellipsis/helloworld
git checkout -b utilities/react-translate-component/helloworld
git checkout -b internationalization-l10n-localization-translation/react-globalize/helloworld
git checkout -b internationalization-l10n-localization-translation/react-i18next/helloworld
git checkout -b internationalization-l10n-localization-translation/react-intl/helloworld
git checkout -b internationalization-l10n-localization-translation/react-translate-maker/helloworld
git checkout -b framework-bindings-integrations/backbone-react-component/helloworld
git checkout -b framework-bindings-integrations/elm-react-component/helloworld
git checkout -b framework-bindings-integrations/gl-react/helloworld
git checkout -b framework-bindings-integrations/react-backbone/helloworld
git checkout -b framework-bindings-integrations/react-d3-library/helloworld
git checkout -b framework-bindings-integrations/react-elm-components/helloworld
git checkout -b framework-bindings-integrations/react-famous/helloworld
git checkout -b framework-bindings-integrations/react-localstorage/helloworld
git checkout -b framework-bindings-integrations/react-on-rails/helloworld
git checkout -b framework-bindings-integrations/react-swf/helloworld
git checkout -b framework-bindings-integrations/react-three-renderer/helloworld
git checkout -b framework-bindings-integrations/reactfire/helloworld
git checkout -b framework-bindings-integrations/reactive-elements/helloworld
git checkout -b integrations-with-third-party-services/react-ga/helloworld
git checkout -b integrations-with-third-party-services/react-google-analytics/helloworld
git checkout -b integrations-with-third-party-services/react-recaptcha/helloworld
git checkout -b integrations-with-third-party-services/react-stripe-checkout/helloworld
git checkout -b integrations-with-third-party-services/redux-segment/helloworld
git checkout -b ui/inferno/helloworld
git checkout -b ui/react-canvas/helloworld
git checkout -b ui/react-fastclick/helloworld
git checkout -b ui/react-static-container/helloworld
git checkout -b inspect/react-perf-tool/helloworld
git checkout -b inspect/react-render-visualizer/helloworld
git checkout -b inspect/why-did-you-update/helloworld
git checkout -b lazy-load/react-infinite-grid/helloworld
git checkout -b lazy-load/react-infinite/helloworld
git checkout -b lazy-load/react-lazy-load/helloworld
git checkout -b lazy-load/react-lazyload/helloworld
git checkout -b lazy-load/react-virtualized/helloworld
git checkout -b app-size/babel-plugin-transform-react-remove-prop-types/helloworld
git checkout -b app-size/react-lite/helloworld
git checkout -b server-side-rendering/react-esi/helloworld
git checkout -b test/carte-blanche/helloworld
git checkout -b test/chai-enzyme/helloworld
git checkout -b test/enzyme/helloworld
git checkout -b test/jest-cli/helloworld
git checkout -b test/legit-tests/helloworld
git checkout -b test/react-unit/helloworld
git checkout -b test/redux-ava/helloworld
git checkout -b test/redux-test-recorder/helloworld
git checkout -b test/ui-harness/helloworld
git checkout -b test/unexpected-react/helloworld
git checkout -b redux/redux-devtools-chart-monitor/helloworld
git checkout -b redux/redux-devtools-dock-monitor/helloworld
git checkout -b redux/redux-devtools-filterable-log-monitor/helloworld
git checkout -b redux/redux-devtools-inspector/helloworld
git checkout -b redux/redux-devtools-log-monitor/helloworld
git checkout -b redux/redux-devtools/helloworld
git checkout -b redux/remote-redux-devtools/helloworld
git checkout -b inspect/fluxguard/helloworld
git checkout -b inspect/react-inspector/helloworld
git checkout -b inspect/react-json-inspector/helloworld
git checkout -b inspect/reactotron/helloworld
git checkout -b miscellaneous/cosmos-js/helloworld
git checkout -b miscellaneous/mighty-react-snippets/helloworld
git checkout -b miscellaneous/react-atellier/helloworld
git checkout -b miscellaneous/react-heatpack/helloworld
git checkout -b miscellaneous/react-styleguidist/helloworld
git checkout -b miscellaneous/standard-react/helloworld
git checkout -b miscellaneous/html-to-react-components/helloworld
git checkout -b miscellaneous/htmltojsx/helloworld
git checkout -b miscellaneous/jsonx/helloworld
git checkout -b miscellaneous/mozaik/helloworld
git checkout -b miscellaneous/react-blessed/helloworld
git checkout -b static-website-generator/gatsby/helloworld
git checkout -b static-website-generator/phenomic/helloworld
