const LYNKED_RED = "#B71D1B";
const LYNKED_WHITE = "#FFFFFF";
const LYNKED_BLACK = "#000000";
const LYNKED_LIGHT_GREY = "#B3B3B3";
const LYNKED_DEEP_GREY = "#9A9A9A";

const LYNKED_GREEN = "#44A048";
const LYNKED_SUCCESS = LYNKED_GREEN;

export {
  LYNKED_RED,
  LYNKED_WHITE,
  LYNKED_BLACK,
  LYNKED_LIGHT_GREY,
  LYNKED_DEEP_GREY,
  LYNKED_SUCCESS,
  LYNKED_GREEN,
};
