react-react-router-history-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        pushd react-react-router-history-tryout
          yarn
          yarn build
        popd