react-lazy-load-image-component-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        pushd react-lazy-load-image-component-tryout
          yarn
          yarn build
        popd