react-stripe-payment-request-button-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        pushd react-stripe-payment-request-button-tryout
          yarn
          yarn build
        popd