name: master_build
on: [push, pull_request]

jobs:

  # 
  # /home/logic/_workspace/react-playlist/react-github-ci-helloworld-tryout/build.yml
  # 
  react-github-ci-helloworld-tryout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          pushd react-github-ci-helloworld-tryout
            yarn
            yarn build
          popd
