react-moment-timezone-tryout:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: |
        pushd react-moment-timezone-tryout
          yarn
          yarn build
        popd